Add models
maxthestranger/rails_blog pull request #2
Opened 2022-07-06 13:12 UTC by maxthestranger

Hello reviewer ✋🏾 

Here are some of the tasks accomplished:

- [x] generated models
- [x] added associations
- [x] fixed linter errors

2022-07-06 13:57 UTC, Mre55 requested changes
**Hi @maxthestranger,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._


<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 13:57 UTC, Mre55 commented on app/models/user.rb
> +  has_many :likes
These all three associations has to have `foreign_key: author_id` in your case since the column name is `user_id` add `foreign_key: user_id`

2022-07-06 13:57 UTC, Mre55 commented on app/models/user.rb
> +end
Kindly, add a method that returns the 3 most recent posts for a given user. As of the project requirement.

2022-07-06 13:57 UTC, Mre55 commented on app/models/user.rb
> +end
Please implement all the tasks required in the [project requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#project-requirements). Add a method method that updates the posts counter for a user and a method which returns the 5 most recent comments for a given post.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/34578631/177565267-1f5a01dc-e7a5-4c57-98f2-6f845b225020.png">

2022-07-06 13:57 UTC, Mre55 commented on app/models/comment.rb
> +  belongs_to :post
<img width="746" alt="image" src="https://user-images.githubusercontent.com/34578631/177567083-f69c2e9e-7cee-43d3-920d-b9cbb171d4c1.png">

2022-07-06 13:57 UTC, Mre55 commented on app/models/like.rb
> +  belongs_to :post
<img width="746" alt="image" src="https://user-images.githubusercontent.com/34578631/177567239-1541793a-2945-4e6f-8b3a-98730237af4b.png">

2022-07-07 13:12 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @maxthestranger,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-15 13:52 UTC, merged